spring:
  datasource:
    url: jdbc:postgresql://${A_DB_HOST:localhost}:${A_DB_PORT:5432}/${A_DB_NAME:autonline}
    driver-class-name: org.postgresql.Driver
    username: autonline_user
    password: autonline123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${A_HIBERNATE_DDL_AUTO:update}
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
# JWT Configuration
app:
  cors:
    allowed-origins: https://autonline.uz,https://www.autonline.uz,http://localhost:3000,https://autonline.up.railway.app,https://autonline-admin.up.railway.app,http://localhost:3001,http://localhost:8080
  jwt:
    secret: ${A_JWT_SECRET:feD65K4oszTmBRZIpO94QVgrqFaByXh72z7cENrVRDIqama4jKsdBAjA14StehYaH0D35Hen5skXYPmhNfY62ZDM1Klo24Jp1pZmTBH6qxsLfFYOSiScncyj9r8iiprRpIHFSVSSbF14CmVxJFdYHHXxDZQQrIA77PwKYFV0NoErQLIo0CZoISDFd7NxecmWmHlqRWSW}
    expiration: ${A_JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh:
      expiration: ${A_JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

# Logging Configuration
logging:
  level:
    uz.javachi.autonline: ${A_LOG_LEVEL:DEBUG}
    org.springframework.security: ${A_SECURITY_LOG_LEVEL:DEBUG}
    uz.javachi.autonline.config.security: DEBUG
server:
  port: ${A_SERVER_PORT:8080}

do:
  space:
    accessKey: DO801WAZYEFG36XNUJER
    secretKey: Hp4mVdehQPoyCQvcqGLAXJFekEQ4avJjMlW4CXj0m3I
    endpoint: https://sfo3.digitaloceanspaces.com
    region: sfo3
    bucket: autonline