create table users
(
    user_id           integer generated by default as identity
        primary key,
    created_at        timestamp(6) not null,
    deleted_at        timestamp(6),
    is_active         boolean      not null,
    next_payment_date timestamp(6),
    password          varchar(255) not null,
    phone_number      varchar(20)  not null
        constraint ukkwds03ohobcd8p6eowkw0f5bm
            unique
        constraint uk9q63snka3mdh91as4io72espi
            unique,
    updated_at        timestamp(6) not null,
    username          varchar(50)  not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table users
    owner to autonline_user;

