apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autonline.fullname" . }}-config
  labels:
    {{- include "autonline.labels" . | nindent 4 }}
data:
  allowed-origins: {{ include "autonline.corsOrigins" . | quote }}
  log-level: {{ .Values.app.logging.level | quote }}
  security-log-level: {{ .Values.app.logging.securityLevel | quote }}
  config-log-level: {{ .Values.app.logging.configLevel | quote }}
