apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autonline.fullname" . }}-secret
  labels:
    {{- include "autonline.labels" . | nindent 4 }}
type: Opaque
data:
  database-username: {{ .Values.database.username | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  jwt-secret: {{ .Values.jwt.secret | b64enc | quote }}
  storage-access-key: {{ .Values.storage.accessKey | b64enc | quote }}
  storage-secret-key: {{ .Values.storage.secretKey | b64enc | quote }}
