apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autonline-app-of-apps
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: autonline
    type: app-of-apps
spec:
  project: default
  
  source:
    repoURL: https://github.com/asadbek-abdinazarov/autonline-backend
    targetRevision: master
    path: argocd/applications
    directory:
      recurse: true
      exclude: app-of-apps.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
